#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
@hostname = http://localhost:3000
@id = 29
@short = "IsOboFA6"
# ============================================================================
#    Entity: short-url
#    Endpoint: /short-url
# ============================================================================

####
#### Redireciona ao url 
#### 
GET {{hostname}}/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects all short-url 
#### 
GET {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects a short-url 
#### 
GET {{hostname}}/v1/short-url/unique/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Create a new short-url 
#### 
POST {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "originalUrl": "https://www.alliancebresilcanada.com/cours-pour-enfants",
    "uniqueId": "pt", 
    "numberClicks": 0, 
    "user": "juliozohar"
}

####
DELETE {{hostname}}/v1/short-url/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json