#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
# @hostname = http://localhost:3001
@hostname = https://shortnsweet.link
@id = 1
@short = "IsOboFA6"
# ============================================================================
#    Entity: short-url
#    Endpoint: /short-url
# ============================================================================

####
#### Redireciona ao url 
#### 
GET {{hostname}}/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects all short-url 
#### 
GET {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects a short-url 
#### 
GET {{hostname}}/v1/short-url/unique/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Create a new short-url 
#### 
POST {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "originalUrl": "didcomm://invite?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiOGU1OGYzZGItMzg3My00NTAyLTliZmEtNzM4MGJkNDczY2Y2IiwgInJlY2lwaWVudEtleXMiOiBbIjcxWXp2RmpLblNyTDQzdFpUVlRRN2k3cHZ4SG5uc1FvVkt2Z25UekpMODc2Il0sICJsYWJlbCI6ICJUZXN0IiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2V4cC1wb3J0LWUtY29uc29tbWF0ZXVyLWFnZW50LmFwcHMuZXhwLm9wZW5zaGlmdC5jcWVuLmNhIn0=",
    "uniqueId": "", 
    "numberClicks": 0, 
    "user": "juliozohar"
}

####
DELETE {{hostname}}/v1/short-url/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json



@access-id=1
@ngrokadress=https://f46b-107-159-197-196.ngrok.io

# Endpoint temporaire entree acces/refus
####
PATCH {{hostname}}/v1/short-url/{{access-id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "originalUrl": "nouveaucrm/webhook/accept"
}
