version: "3"

services:
  db:
    container_name: ${APP}-postgresdb-${SUFFIX}
    image: postgres:15.1
    ports:
      - 35432:5432
    networks:
      - ${NETWORK}
    volumes:
      - ./data/postgres-data:/data/postgres
    restart: always
    env_file:
      - .env

  api:
    container_name: ${APP}-api-${SUFFIX}
    image: shortnsweet-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8024:3000
    networks: 
      - ${NETWORK}
    restart: unless-stopped
    depends_on: 
      - db

networks:
  shortnsweet-network: