version: "3"

services:
  db:
    container_name: ${APP}-mysqldb-${SUFFIX}
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3307
    env_file:
      - .env
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - ${NETWORK}

  #adminer: 
  #  container_name: ${APP}-adminer-${SUFFIX}
  #  image: adminer
  #  restart: always
  #  ports: 
  #    - 8889:8080
  #  depends_on:
  #    - db
  #  networks:
  #    - ${NETWORK}

  #omnidb:
  #  container_name: ${APP}-omniDb-${SUFFIX}
  #  image: taivokasper/omnidb
  #  restart: always
  #  volumes:
  #    - ./data/omnidb:/etc/omnidb 
    #links:
    #  - postgres:postgres
  #  ports:
  #    - "8090:8080"
  #    - "25482:25482"
  #  networks:
  #    - ${NETWORK}

  #omniDb:
  #  container_name: ${APP}-omniDb-${SUFFIX}
  #  image: omnidbteam/omnidb:latest
  #  restart: always
  #  links:
  #    - postgres:postgres
  #  ports:
  #    - 8889:8080
  #  volumes: 
  #    - ./data/omnidb:/home/omnidb/.omnidb/omnidb-server
  #  networks:
  #    - ${NETWORK}

  api:
    container_name: ${APP}-api-${SUFFIX}
    image: shortnsweet-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks: 
      - ${NETWORK}
    restart: unless-stopped
    depends_on: 
      - db

networks:
  shortnsweet-network: